services:
  - type: web
    name: wird-muslim-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python wird_bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: RENDER
        value: "true"
      - key: PYTHON_VERSION
        value: "3.11.0"